# -*- ruby -*-

require "rubygems"
require "hoe"
require 'rake/extensiontask'

# Hoe.plugin :compiler
# Hoe.plugin :gem_prelude_sucks
# Hoe.plugin :inline
# Hoe.plugin :minitest
# Hoe.plugin :racc
# Hoe.plugin :rcov
# Hoe.plugin :rdoc

Hoe.spec "ohlist" do
  # HEY! If you fill these out in ~/.hoe_template/default/Rakefile.erb then
  # you'll never have to touch them again!
  # (delete this comment too, of course)

  developer("Adam Pahlevi Baihaqi", "adam.pahlevi@gmail.com")

  self.extra_dev_deps << ['rake-compiler', '>= 0']
  self.spec_extras = { extensions: ['ext/ohlist/extconf.rb'] }

  Rake::ExtensionTask.new('ohlist', spec) do |ext|
    ext.lib_dir = File.join('lib', 'ohlist')
  end

  # license "MIT" # this should match the license in the README
end

# vim: syntax=ruby
